postgresql:
    HOST: 'localhost'
    USER: 'user'
    PASSWD: 'user'
    DATABASE: 'database'
    SCHEMA: 'schema'
    TABLE: 'table'
    PORT: 'port'

spaces:
    REGION_NAME: 'nyc3'
    ENDPOINT_URL: 'https://nyc3.digitaloceanspaces.com'
    ACCESS_KEY_ID: 'ACCESS_KEY'
    SECRET_ACCESS_KEY: 'SECRET_KEY'
    BUCKETNAME: 'your bucket name'
    SPACESPATH: 'path for publicly available link to bucket'
    SPACESDIR: 'Folder/Directory you want to keep the file in'
